# render.yaml

envVarGroups:
  - name: prod-secrets
  - name: hml-secrets
  - name: dev-secrets

services:
  # --- SERVIÇO DE PRODUÇÃO ---
  - type: web
    name: checklist-api-prod # <-- MUDE SE NECESSÁRIO
    env: python
    repo: https://github.com/Marcosdev03/projeto_checklistv02.git # <-- CONFIRME SEU REPO
    branch: main
    envVarGroups:        # <-- CORREÇÃO: Alinhado com 'type', 'name', etc.
      - prod-secrets
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=config.settings.prod
    startCommand: |
      python manage.py migrate --settings=config.settings.prod && gunicorn config.wsgi --bind 0.0.0.0:$PORT --settings=config.settings.prod
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: PYTHON_VERSION
        value: '3.11'
      - key: WEB_CONCURRENCY
        value: 4

  # --- SERVIÇO DE HOMOLOGAÇÃO ---
  - type: web
    name: checklist-api-hml # <-- MUDE SE NECESSÁRIO
    env: python
    repo: https://github.com/Marcosdev03/projeto_checklistv02.git # <-- CONFIRME SEU REPO
    branch: homolog
    envVarGroups:        # <-- CORREÇÃO: Alinhado com 'type', 'name', etc.
      - hml-secrets
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=config.settings.hml
    startCommand: |
      python manage.py migrate --settings=config.settings.hml && gunicorn config.wsgi --bind 0.0.0.0:$PORT --settings=config.settings.hml
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.hml
      - key: PYTHON_VERSION
        value: '3.11'
      - key: WEB_CONCURRENCY
        value: 2

  # --- SERVIÇO DE DESENVOLVIMENTO ONLINE ---
  - type: web
    name: checklist-api-dev # <-- MUDE SE NECESSÁRIO
    env: python
    repo: https://github.com/Marcosdev03/projeto_checklistv02.git # <-- CONFIRME SEU REPO
    branch: develop
    envVarGroups:        # <-- CORREÇÃO: Alinhado com 'type', 'name', etc.
      - dev-secrets
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=config.settings.dev
    startCommand: |
      python manage.py migrate --settings=config.settings.dev && gunicorn config.wsgi --bind 0.0.0.0:$PORT --settings=config.settings.dev
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.dev
      - key: PYTHON_VERSION
        value: '3.11'
      - key: WEB_CONCURRENCY
        value: 1